FROM maven:3.3.9-jdk-8

MAINTAINER Tobias Flohre <tobias.flohre@codecentric.de>

VOLUME /root/.m2

VOLUME /data

WORKDIR /data/jobs/edmp-sample-stream-source-1-docker-build-run/workspace

CMD mvn clean install
