FROM maven:3.3.9-jdk-8

MAINTAINER Tobias Flohre <tobias.flohre@codecentric.de>

CMD clean versions:set -DnewVersion=${BUILD_NUMBER} -U && mvn clean deploy -DaltDeploymentRepository=nexus-release-repository::default::http://nexus:8081/nexus/content/repositories/releases/ -U